
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js
node_js: 
  - '6.10.3'

before_install: 
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g @angular/cli@1.0.1
  - npm install -g mocha
  - npm install -g jasmine

script: 
  - cd angular-src
  - npm install
  - ng e2e